apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuapp-deployment
  labels:
    app: redis
    tipo: cache
    time: infra
spec:
  template:
    metadata:
      name: meuapp-pod
      labels:
        app: meuapp-redis
        tipo: cache
    spec:
      containers:
      - name: redis-container
        image: redis
  replicas: 3
  selector:
    matchLabels:
      tipo: cache