name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    #- name: Build
    #  run: go build -v ./exercicios/*.go

    - name: Run
      env:
        EXERCICIOS: exercicios/*.go
      run: |
        for exercicio in $EXERCICIOS; do go run $exercicio; done
      #for exercicio in exercicios/*.go; do go run ./exercicios/*.go; done
