name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: output pipeline
      uses: Code-Hex/neo-cowsay-action@v1
      with:
        message: 'Hora de rodar nossos exercícios...'
        cow: 'gopher'

    - name: Run
      env:
        EXERCICIOS: exercicios/*.go
      run: |
        for exercicio in $EXERCICIOS; do echo "-_-_-_-_-_-_-_-"; \
        echo " "; \
        echo "Rodando exercício $exercicio"; \
        echo " "; \
        go run $exercicio; \ 
        echo " "; \
        done
