name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: output pipeline
      uses: Code-Hex/neo-cowsay-action@v1
      with:
        message: 'Hora de rodar nossos exercícios...'
        cow: 'gopher' # ascii art list: https://github.com/Code-Hex/Neo-cowsay/tree/master/cows

    - name: Run
      env:
        EXERCICIOS: exercicios/*.go
      run: |
        for exercicio in $EXERCICIOS; do cowsay "Rodando exercício $exercicio"; go run $exercicio; done
      #for exercicio in exercicios/*.go; do go run ./exercicios/*.go; done
